<?php 
include('../assets/main/css/bootstrap.css.php');
include('../assets/main/css/gritter.css.php');
include('../assets/main/css/bootstrap-editable.css.php');
include('../assets/main/css/font.awesome.css.php');
include('../assets/main/css/google.fonts.css.php');
include('../assets/main/css/chosen.css.php');
include('../assets/main/css/basic.css.php');
include('../assets/main/ckeditor.php');
include('../assets/main/css/fancybox.css.php');
include('../assets/main/css/datatable.css.php');
include('../assets/main/css/datepicker.css.php');
include('../assets/main/css/select.css.php');
///////////////////////////
/*include('../assets/main/css/toastr.css.php');*/
include('../assets/main/css/sweetalert.css.php');
?>