<?php 
include('../assets/main/js/jquery.js.php');
include('../assets/main/js/bootstrap.js.php');
include('../assets/main/js/gritter.js.php');
include('../assets/main/js/bootstrap-editable.js.php');
include('../assets/main/js/datatable.js.php');
/////////////////////////////
/*include('../assets/main/js/toastr.js.php');
include('../assets/main/toastr.php');*/
include('../assets/main/js/sweetalert.js.php');
include('../assets/main/sweetalert.php');
////////////////////////////
include('../assets/main/js/basic.js.php');
//include('../assets/main/js/form_validation.js.php');
include('../assets/main/js/fancybox.js.php');
include('../assets/main/js/checkbox.js.php');
include('../assets/main/js/datepicker.js.php');
include('../assets/main/image.validation.js.php');
include('../assets/main/js/validation.js.php');
include('../assets/main/js/chosen.js.php');
include('../assets/main/js/select.js.php');

?>